### ISSUE TITLE
Push 4.1.1 to Maven

### ISSUE THREAD

**Issue by redhell** [vlsi/jgraphx-publish#4]
Can you push the branch to maven please?

**Comment by vlsi** [comment]
Ah, I was sure the build was there, however, it looks like I forgot to "release the staged repository".
Will publish it shortly

**Comment by vlsi** [comment]
I've pushed 4.1.1 to Central, and it would appear shortly at https://repo1.maven.org/maven2/com/github/vlsi/mxgraph/jgraphx/

**Comment by redhell** [comment]
@vlsi Thanks but can you update to the last version 4.2.2?

**Comment by vlsi** [comment]
I've published 4.2.0, 4.2.1, and 4.2.2
